In [1]:
import numpy as np

In [11]:
ar1d=np.array([1,2,3,4])
print(ar1d)
type(ar1d)
np.ndim(ar1d)

[1 2 3 4]


1

In [12]:
ar2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar2d)
np.ndim(ar2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [13]:
ar3d=np.array([[[1,2],[3,4],[5,6]]])
print(ar3d)
np.ndim(ar3d)

[[[1 2]
  [3 4]
  [5 6]]]


3

# there are diff ways to create array

In [14]:

# np.array([])
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [15]:
b=np.arange(10,100,10)   #using arange
b                         #creates array from 10 to 100 with step 10

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
c=np.linspace(0,10,5) #using linspace
c                     #5 values eveenly spaced b/w 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
d=np.logspace(0,10,5)  #5 log values b/w 0 to 10 
d

array([1.00000000e+00, 3.16227766e+02, 1.00000000e+05, 3.16227766e+07,
       1.00000000e+10])

In [19]:
e=np.zeros(10,int)
e

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
e=np.zeros((10,5))
e

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
f=np.ones(5,dtype=int)
f

array([1, 1, 1, 1, 1])

In [22]:
f=np.ones((3,5))
f

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
g=np.eye(4)   #prints 4x4 identity matrix
g

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
full_array=np.full((3,3),7)      #prints the complete array
full_array

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

<!-- numpy array properties
shape size type -->

# properties /shape,size,type,ndim,astype

In [28]:
arr2=np.array([[1,2,3],[4,5,6]])           #shape
print(arr2)
arr2.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [29]:
arr2=np.array([[1,2,3],[4,5,6]])           #size
print(arr2)
arr2.size

[[1 2 3]
 [4 5 6]]


6

In [30]:
arr2=np.array([[1,2,3],[4,5,6]])            #number of dimensions
print(arr2)
np.ndim(arr2)

[[1 2 3]
 [4 5 6]]


2

In [32]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
arr2.ndim

[[1 2 3]
 [4 5 6]]


2

In [37]:
arr2=np.array([[1,2,3],[4,5,6]])         #dtype
print(arr2)
arr2.dtype    


[[1 2 3]
 [4 5 6]]


dtype('int64')

In [38]:
arr2=np.array([[1,2,3],[4,5,6]])          #change data type
print(arr2)
arr3=arr2.astype(float)
arr3

[[1 2 3]
 [4 5 6]]


array([[1., 2., 3.],
       [4., 5., 6.]])

# mathametical functions

In [43]:
arr=np.array([1,2,3,4,5,6])

print(arr+5)
print(arr*2)
print(arr**2)   
print(arr-5)
print(arr/2)
print(arr//2)       #same all
print(arr%2)


[ 6  7  8  9 10 11]
[ 2  4  6  8 10 12]
[ 1  4  9 16 25 36]
[-4 -3 -2 -1  0  1]
[0.5 1.  1.5 2.  2.5 3. ]
[0 1 1 2 2 3]
[1 0 1 0 1 0]


<!-- aggregration functions   sum,mean,max,min,std,variance -->

# aggeragation fns sum,mean,min,max,std,var

In [41]:
arr=np.array([1,2,3,4,5,6])

print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

21
3.5
1
6
1.707825127659933
2.9166666666666665


#indexing,slicing

In [48]:
arr=np.array([10,20,30,40])  #accesing elements 
print(arr[2])

#2d array - arr[row,column]
#3d array - arr[2,3,4]

#accesing multiple elemnts
print(arr[[0,3,1]])

[10 40 20]


In [47]:
#slicing

#array[start:stop:step]
# -1 reverse array


In [ ]:
#reshaping